schema_version = "1.0.0"

id = "merge_vertex_groups_rknz"
name = "Merge Vertex Groups RKNZ"
version = "1.2.0"
tagline = "Combine multiple vertex groups into one using Max, Add, or Average blending"
maintainer = "Rikokenz <https://github.com/rikokenz>"
type = "add-on"
website = "https://github.com/rikokenz/Merge-Vertex-Groups-RKNZ"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
